"""user - add memo

Revision ID: f68ea4b1d8d0
Revises: a8366cef738d
Create Date: 2026-06-04 04:40:35.856996

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f68ea4b1d8d0"
down_revision: Union[str, None] = "a8366cef738d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("memo", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "memo")
    # ### end Alembic commands ###
